name: context

on:
  push:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository ${{ github.repository }}"
      - run: echo "Branch ${{ github.ref_name }}"
      - run: echo "SHA ${{ github.sha }}"
      - run: echo "Event ${{ github.event_name }}"
      - run: echo "OS ${{ runner.os }}"
