name: context

on:
  push:

jobs:
  context:
    runs-on: ubuntu-latest

    steps:
      - name: Print context
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.sha }}"
          echo "${{ github.event_name }}"
          echo "${{ runner.os }}"
